# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 062e0d5d851ae36daae8ad92fc6636b6ffdc9d70ec518451c745e31a3adf403cc1df85b28478a7c92b67a177209642c2dd3e467bcdde13326b5e6c016a918822

test:
  secret_key_base: 601595ee46a20742d096711747aed1be3965c81bc2ba4e56619fb34d54be522e78383e375dc21f00c597692fb8ce3b19d5970c069461f15b081f1c46cdb20402

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
